# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- feature/*

pool:
  vmImage: ubuntu-latest

resources:
- repo: self

variables:
  - group: aws
  - name: tag
    value: '$(Build.BuildId)'
  - name: DOCKER_REPOSITORY
    value: $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/autologgids-dev
  - name: DOCKER_REPOSITORY_STAGING
    value: $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/autologgids-staging
  - name: DOCKER_REPOSITORY_PROD
    value: $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/autologgids-prod

stages:
  - stage: Build
    displayName: Build
    jobs:
    - job: Build
      displayName: Build
      steps:
        - task: Bash@3
          displayName: 'Login to ECR'
          inputs:
            targetType: 'inline'
            script: |
                aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com
          env:
            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

        - task: Bash@3
          displayName: 'Build theme'
          inputs:
            workingDirectory:  build/keycloak
            targetType: 'inline'
            script: |
              chmod 755 package.sh
              ./package.sh autologg

        - task: Docker@2
          displayName: Build an image
          inputs:
            command: build
            buildContext: $(Build.SourcesDirectory)/build/keycloak
            dockerfile: '$(Build.SourcesDirectory)/build/keycloak/Dockerfile'
            tags: |
              $(DOCKER_REPOSITORY):$(Build.BuildId)
              $(DOCKER_REPOSITORY):$(Build.BuildNumber)
              $(DOCKER_REPOSITORY):latest
              $(DOCKER_REPOSITORY_STAGING):$(Build.BuildId)
              $(DOCKER_REPOSITORY_STAGING):$(Build.BuildNumber)
              $(DOCKER_REPOSITORY_STAGING):latest
            arguments: -t $(DOCKER_REPOSITORY):$(Build.BuildId) -t $(DOCKER_REPOSITORY):latest -t $(DOCKER_REPOSITORY):$(Build.BuildNumber) -t $(DOCKER_REPOSITORY_STAGING):$(Build.BuildId) -t $(DOCKER_REPOSITORY_STAGING):latest -t $(DOCKER_REPOSITORY_STAGING):$(Build.BuildNumber)
        - task: Docker@2
          inputs:
            repository: $(DOCKER_REPOSITORY)
            command: 'push'
            tags: | 
              latest
              $(Build.BuildId)
              $(Build.BuildNumber)
        - task: Docker@2
          inputs:
            repository: $(DOCKER_REPOSITORY_STAGING)
            command: 'push'
            tags: | 
              latest
              $(Build.BuildId)
              $(Build.BuildNumber)              

              